<?php
G::LoadClass("plugin");

class er2Plugin extends PMPlugin
{

  public function er2Plugin($sNamespace, $sFilename = null)
  {
    $res = parent::PMPlugin($sNamespace, $sFilename);
    $this->sFriendlyName = "er2 Plugin";
    $this->sDescription  = "Autogenerated plugin for class er2";
    $this->sPluginFolder = "er2";
    $this->sSetupPage    = "setup";
    $this->iVersion      = 0.17;
    //$this->iPMVersion    = 2425;
    $this->aWorkspaces   = array('workflow', 'HSU', 'HSUx');
    //$this->aWorkspaces = array("os");

    return $res;
  }

  public function setup()
  {
    //$this->registerMenu("processmaker", "menuer2.php");
    $this->registerPmFunction();
  }

  public function install()
  {

  }

  public function enable()
  {

  }

  public function disable()
  {

  }

}

$oPluginRegistry = &PMPluginRegistry::getSingleton();
$oPluginRegistry->registerPlugin("er2", __FILE__);
